Procfile, build.sbt, project/build.properties, project/plugins.sbt, src/main/scala/wordbots/Parser.scala, src/main/scala/wordbots/Server.scala, src/main/scala/wordbots/WordbotsServer.scala
http://wordbots.herokuapp.com/
=> Heroku server

src/main/scala/wordbots/CodeGenerator.scala, src/main/scala/wordbots/Lexicon.scala, src/main/scala/wordbots/StrictIntegerMatcher.scala, src/main/scala/wordbots/semantics.scala, src/test/scala/wordbots/ParserSpec.scala
=> A collection of new parsed phrases based on 4/10/17 playtest

README.md
=> added patreon link to readme

src/main/scala/wordbots/AstValidator.scala, src/main/scala/wordbots/Lexicon.scala, src/main/scala/wordbots/semantics.scala, src/test/scala/wordbots/ParserSpec.scala
Fix https://github.com/wordbots/wordbots-core/issues/616.
=> Correctly parse 'Whenever a card is played, this robot becomes a copy of it'

src/main/scala/wordbots/Lexicon.scala, src/test/scala/wordbots/ParserSpec.scala
=> Parse '[triggered ability], and [triggered ability]'

src/main/scala/wordbots/CodeGenerator.scala, src/main/scala/wordbots/Lexicon.scala, src/main/scala/wordbots/semantics.scala, src/test/scala/wordbots/ParserSpec.scala
#69.
See also https://github.com/wordbots/wordbots-core/pull/693.
=> Parse 'Activate: Deal 1 damage to a robot 3 tiles away'

src/main/scala/wordbots/AstValidator.scala, src/main/scala/wordbots/CodeGenerator.scala, src/main/scala/wordbots/Lexicon.scala, src/main/scala/wordbots/semantics.scala, src/test/scala/wordbots/ParserSpec.scala
I worked off of https://github.com/MichaelEbert/wordbots-parser/tree/creation-effects-statparsing, cleaned some things up, changed the semantics and JavaScript output of GeneratedCard somewhat, and added support for stats triples.
Supersedes #78.
=> Object creation effects

src/main/scala/wordbots/Lexicon.scala, src/test/scala/wordbots/ParserSpec.scala
https://github.com/wordbots/wordbots-core/issues/710
=> Support noun form of 'enemy' to mean 'any enemy object'

src/main/scala/wordbots/Lexicon.scala, src/test/scala/wordbots/ParserSpec.scala
=> Parse 'At the start of your turn, if you have a robot on the board with 3 or more health, draw 2 cards'

build.sbt, src/main/scala/wordbots/Server.scala
=> Proper JSON serialization in http responses using Circe

src/main/scala/wordbots/ErrorAnalyzer.scala
=> Fall back to syntactic suggestions if there are no semantic suggestions

build.sbt, src/main/scala/wordbots/CodeGenerator.scala, src/main/scala/wordbots/Parser.scala, src/main/scala/wordbots/Server.scala, src/test/scala/wordbots/ParserSpec.scala
=> Use Rhino to parse generated JavaScript to ensure it's valid

src/main/scala/wordbots/Lexicon.scala, src/main/scala/wordbots/semantics.scala, src/test/scala/wordbots/ParserSpec.scala
See also https://github.com/wordbots/wordbots-core/pull/1100 .
=> Parse 'Each robot's attack and speed become equal to its health' (fix #126)

src/main/scala/wordbots/AstValidator.scala, src/main/scala/wordbots/CodeGenerator.scala, src/main/scala/wordbots/Lexicon.scala, src/main/scala/wordbots/semantics.scala, src/test/scala/wordbots/ParserSpec.scala
https://github.com/wordbots/wordbots-core/issues/1104
=> Allow spawning enemy objects

src/main/scala/wordbots/Lexicon.scala, src/main/scala/wordbots/semantics.scala, src/test/scala/wordbots/ParserSpec.scala
=> Parse 'cannotmove' and 'cannotactivate' effects

src/main/scala/wordbots/CodeGenerator.scala, src/main/scala/wordbots/Lexicon.scala, src/main/scala/wordbots/semantics.scala, src/test/scala/wordbots/ParserSpec.scala
=> Parse 'Deal 3 damage to your kernel for each robot in play'

src/main/scala/wordbots/CodeGenerator.scala, src/main/scala/wordbots/Lexicon.scala, src/main/scala/wordbots/semantics.scala, src/test/scala/wordbots/ParserSpec.scala
=> Parse 'Robots with even power can't attack'

src/main/scala/wordbots/CodeGenerator.scala, src/main/scala/wordbots/Lexicon.scala, src/main/scala/wordbots/semantics.scala, src/test/scala/wordbots/ParserSpec.scala
=> Parse 'This robot has +4 attack if your discard pile has 5 or more cards'

build.sbt, src/main/scala/wordbots/AstValidator.scala, src/main/scala/wordbots/CodeGenerator.scala, src/main/scala/wordbots/ErrorAnalyzer.scala, src/main/scala/wordbots/Lexicon.scala, src/main/scala/wordbots/Parser.scala, src/main/scala/wordbots/Semantics.scala, src/main/scala/wordbots/Server.scala, src/main/scala/wordbots/semantics.scala, src/test/scala/wordbots/ParserSpec.scala, src/test/scala/wordbots/Randomizer.scala
#148
Example output:
```
[
"(function () { actions['shuffleCardsIntoDeck'](targets['random'](count(other(cardsInHand(targets['itP'](), 'anycard'))), cardsInHand(targets['self'](), 'structure')), targets['theyP']()); })",
"(function () {actions['become'](targets['it'](),targets['copyOf'](targets['they']()));})",
"(function () { actions['swapAttributes'](targets['thisRobot'](), 'attack', 'speed'); })",
"(function () { actions['giveAbility'](targets['it'](), \"(function () { setAbility(abilities['attributeAdjustment'](function () { return tilesMatchingConditions([]); }, 'speed', function (x) { return Math.ceil(x / attributeSum(other(objectsMatchingConditions('robot', [])), [])); })); })\"); })",
"(function () { actions['takeControl'](targets['controllerOf'](targets['that']()), …
```
=> Random action generator (to be used for testing)

build.sbt, src/main/scala/wordbots/AstValidator.scala, src/main/scala/wordbots/CodeGenerator.scala, src/main/scala/wordbots/ErrorAnalyzer.scala, src/main/scala/wordbots/Lexicon.scala, src/main/scala/wordbots/Semantics.scala, src/test/scala/wordbots/ParserSpec.scala
#152, #153, #154, #155, #156, #157, #158, #159, #161.
Corresponding wordbots-core tickets: https://github.com/wordbots/wordbots-core/issues/1158, https://github.com/wordbots/wordbots-core/issues/1159, https://github.com/wordbots/wordbots-core/issues/1160
=> New parser features based on James 7/5/19 playtest feedback

src/main/scala/wordbots/CodeGenerator.scala, src/main/scala/wordbots/Lexicon.scala, src/main/scala/wordbots/Semantics.scala, src/test/scala/wordbots/ParserSpec.scala
fix #201, fix #202, fix #203, fix #204, fix #205, fix #206, fix #207, fix #208, fix #209.
=> Many new parses and some bugfixes from 4/25/22 James playtest

src/main/scala/wordbots/AstValidator.scala, src/main/scala/wordbots/CodeGenerator.scala, src/main/scala/wordbots/Lexicon.scala, src/main/scala/wordbots/Semantics.scala, src/test/scala/wordbots/ParserSpec.scala
=> Parsing support for choosing up to 4 targets at a time for ChooseO, ChooseT, or ChooseC
